### ISSUE TITLE
motion-game config

### ISSUE THREAD

**Issue by hugoerg56** [HipByte/motion-fabric#9]
typing rake fabric:setup im getting ERROR! Fabric's api_key cannot be empty

on my ios.rb I have:

app.fabric do |config|
   config.api_key = “….."
   config.build_secret = “…….."
   config.kit 'Crashlytics'
 end

**Comment by MarkVillacampa** [comment]
Can you run the rake command with `--trace` and paste the full stack trace?

**Comment by hugoerg56** [comment]
```
** Invoke fabric:setup (first_time)
** Execute fabric:setup
** Execute build:simulator
rm -f ./build/iPhoneSimulator-10.1-Development/Untitled.app/Info.plist
/usr/bin/plutil -convert binary1 "./build/iPhoneSimulator-10.1-Development/Untitled.app/Info.plist"
** Execute fabric:dsym:simulator
    ERROR! Fabric's api_key cannot be empty
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/motion-fabric-0.7/lib/motion-fabric.rb:112:in `fabric_setup'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/motion-fabric-0.7/lib/motion-fabric.rb:133:in `fabric_run'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/motion-fabric-0.7/lib/motion-fabric.rb:192:in `block (3 levels) in <top (required)>'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/motion-fabric-0.7/lib/motion-fabric.rb:145:in `block (2 levels) in <top (required)>'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/hugorincon/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/bin/rake:23:in `load'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/bin/rake:23:in `<main>'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/bin/ruby_executable_hooks:15:in `eval'
/Users/hugorincon/.rvm/gems/ruby-2.2.0@buildanddestroy/bin/ruby_executable_hooks:15:in `<main>'
```
